### ISSUE TITLE
Add Spout Sender to registry

### ISSUE THREAD

**Issue by Alberthalbautomaten** [keijiro/KlakSpout#101]
Hey there!
I want to use your great plugin to stream a spout source to NVIDIA Broadcast. I can not see the source there. The Spout Receiver does in fact receive it though. I think NVIDIA Broadcast needs the spout source to be registered. Any chance you know how to do that? I know how to write to the registry but i don't know where and what values so that every program sees the sources. Help is much appreciated! :)

**Comment by keijiro** [comment]
Does NVIDIA Broadcast support Spout?

**Comment by Alberthalbautomaten** [comment]
Yes it does, but needs the sources to be registered, otherwise it won't recognize them.

**Comment by keijiro** [comment]
Does it (NVIDIA Broadcast) recognize other Spout sources?
