### ISSUE TITLE
Null Reference Exception for Blitter resource

### ISSUE THREAD

**Issue by kwabbott** [keijiro/KlakSpout#105]
Spout was working fine previously in my 2021.3.29 project, then it suddenly starting throwing the following error. It is somehow tied to the Render Texture. I've uninstalled and reinstalled several times with no success. Klak.Spout is working for for me in several other project.

NullReferenceException: Object reference not set to an instance of an object
Klak.Spout.Blitter.GetMaterial (Klak.Spout.SpoutResources resrc) (at ./Library/PackageCache/jp.keijiro.klak.spout@2.0.3/Runtime/Internal/Utility.cs:45)
Klak.Spout.Blitter.Blit (Klak.Spout.SpoutResources resrc, UnityEngine.Texture src, UnityEngine.RenderTexture dst, System.Boolean alpha) (at ./Library/PackageCache/jp.keijiro.klak.spout@2.0.3/Runtime/Internal/Utility.cs:25)
Klak.Spout.SpoutSender.Update () (at ./Library/PackageCache/jp.keijiro.klak.spout@2.0.3/Runtime/SpoutSender.cs:112)

thanks!

**Comment by keijiro** [comment]
Please try removing the Spout component and re-add it.

**Comment by keijiro** [comment]
I close this issue at the moment. Please reopen it if it still reproduces.
