### ISSUE TITLE
Alpha is lost in builds (URP)

### ISSUE THREAD

**Issue by Auros** [keijiro/KlakSpout#108]
* Unity Version: Unity 2022.3.18f1
* KlakSpout Version: 2.0.3
* Render Pipeline: URP

The spout sender(s) work as normal in Editor, but when making a build, transparency effects are lost.

I'm not sure if there's a setting I'm not aware of which is causing this behaviour when building. I've also overridden the URP post processing shader to support transparency, but I've disabled PP while trying to debug this.

**Editor**
![image](https://github.com/keijiro/KlakSpout/assets/41306347/7e5f91ac-f385-4a79-9a5a-6ee4c0fe530d)

**Build**
![image](https://github.com/keijiro/KlakSpout/assets/41306347/fa00a85e-b207-42c7-b2ed-cdb75e9a3bbb)

**Comment by keijiro** [comment]
How about investigating the development build with Frame Debugger? You can determine when the alpha is lost in the pipeline.

**Comment by Auros** [comment]
I completely forgot you can frame debug builds, I found my issue, I had the wrong render pipeline settings set as the default for the platform.

Thank you, I'll close this now.
