### ISSUE TITLE
UnityRegisterRenderingPlugin on windows 

### ISSUE THREAD

**Issue by GongKuiJun** [keijiro/KlakSpout#111]
On the Windows platform, it is desired to call "UnityRegisterRenderingPlugin" in UNITYWEBGL or "UnityRegisterRenderingPlugin V5" in Native RenderingPlugin IOS

**Comment by keijiro** [comment]
Sorry but I can't understand what you are trying to tell. Spout is a Windows-only library. It's not relevant to WebGL nor iOS.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it's still relevant.
