### ISSUE TITLE
Is this unrelated to building the Unity project?

### ISSUE THREAD

**Issue by ChangSH0106** [keijiro/KlakSpout#112]
Is this unrelated to building the Unity project? I want to combine the built Unity project with TouchDesigner to create the final product.

**Comment by keijiro** [comment]
Sorry, but I’m having trouble understanding your question. Just to clarify, this package is not required for building a Unity project, so you should be able to proceed without it.

**Comment by keijiro** [comment]
I close this issue as answered.
