### ISSUE TITLE
32-bit version?

### ISSUE THREAD

**Issue by Willjfield** [keijiro/KlakSpout#14]
This is fantastic and is working great on 64-bit builds. I don't see anything in docs about it being 64-bit only but I can't get it to work for 32-bit builds. Is it possible to make this work for 32-bit or is the plugin 64-bit only? If so, this should be noted in docs.

**Comment by keijiro** [comment]
Yes. I should note it in README (I just forgot mentioning it).

**Comment by keijiro** [comment]
I added x86 support in the [latest version](https://github.com/keijiro/KlakSpout/releases/tag/v0.1.3), so this issue was solved.

I'm closing this issue. Please feel free to reopen for further questions.
