### ISSUE TITLE
Run on HDRP?

### ISSUE THREAD

**Issue by TxTx123** [keijiro/KlakSpout#16]
KlakSpout don't send graphic on Unity2018.2 with HDRP.
I can send Image without HDRP.

How to use KlakSpout on HDRP mode?
Best regards,

**Comment by keijiro** [comment]
Render texture mode was added in v0.2.0. You can use this mode to send frames rendered with HDRP.

https://github.com/keijiro/KlakSpout/releases/tag/v0.2.0

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
