### ISSUE TITLE
Feature Request - RenderTexture sending mode

### ISSUE THREAD

**Issue by Harvey3141** [keijiro/KlakSpout#17]
Hi, 

It would be useful to have the same RenderTexture sending mode as you have implemented in the NDI plugin, where you can RenderTexture directly via spout without using a camera. 

Thanks, 

Harvey

**Comment by keijiro** [comment]
I'm working on it. Please stay tuned. https://github.com/keijiro/KlakSpout/tree/dev-v0.2

**Comment by keijiro** [comment]
Render texture mode was added in v0.2.0.

https://github.com/keijiro/KlakSpout/releases/tag/v0.2.0

I'm closing the issue now. Please feel free to reopen for further questions.
