### ISSUE TITLE
Crash after adding Spout Receiver

### ISSUE THREAD

**Issue by sasa42** [keijiro/KlakSpout#19]
Unity 2018.2.8f1
or
Unity 2018.2.6f1
Dx 11
KlakSpout Version 0.2
Windows 10 Enterprise

[Crash_2018-09-18_113945015.zip](https://github.com/keijiro/KlakSpout/files/2392521/Crash_2018-09-18_113945015.zip)

Create empty project in 2018.2.8f1 or Unity 2018.2.6f1
import KlakSpout.unitypackage v0.2
Create Empty
Add Component Spout Receiver
Crash

Spout version update and x86 support is working fine.

**Comment by keijiro** [comment]
Thanks for porting the issue. I fixed it in v0.2.1.

https://github.com/keijiro/KlakSpout/releases/tag/v0.2.1

**Comment by keijiro** [comment]
I'm closing this issue (assuming it's fixed in the latest version). Please feel free to reopen if it still reproduces.
