### ISSUE TITLE
Support changing sender dimensions

### ISSUE THREAD

**Issue by Harvey3141** [keijiro/KlakSpout#2]
Hi, 

It would be useful to have the UpdateSender function (SpoutSender.h, line 44) from the SpoutSDK available in Unity. This would you mean you don't have to recreate the spout sender when changing sender dimensions.

Thanks, Harvey

**Comment by keijiro** [comment]
It might be useful, but the priority is low because I rarely change dimensions of senders while playing. It's my personal opinion though.

**Comment by keijiro** [comment]
It's supported on v0.1.2

**Comment by Harvey3141** [comment]
Thanks!
