### ISSUE TITLE
CPU mode support

### ISSUE THREAD

**Issue by erikhric** [keijiro/KlakSpout#20]
I can see all of my spout senders in resolume arena and in any demo app for receiving spout input. 
When I play any of the streams I always get only blank black screen. 
Has anybody had this issue before? Can specific graphics card be problem? 
When I play demo app I can receive any other spout application even the demo itself.

**Comment by keijiro** [comment]
Which "demo app" are you trying? Is it a demo sender/receiver app included in the official Spout package, or example scenes included in this package (KlakSpout)?

**Comment by erikhric** [comment]
I'm using Unity Scene Included in project to receive output from Spout sample sender and it works.
But when I try to do the opposite - stream from unity via KlakSpout to demo receiver or resolume arena I get only black screen. All of the senders are listed, but when I select them they only show black screen.
Thank you for your assistance in this matter.

**Comment by keijiro** [comment]
Thanks for clarification. Hmm, weird. The sender implementation is fairly simple and rarely has trouble. Could you send the [editor log](https://docs.unity3d.com/Manual/LogFiles.html)? I'd like to look into it.

**Comment by erikhric** [comment]
Thank you for the quick reply. Here is the log file:
[Editor.log](https://github.com/keijiro/KlakSpout/files/2419729/Editor.log)

Spout demo sender is working flawlessly in Resolume Arena:
![spout-cam1-working](https://user-images.githubusercontent.com/5880119/46081311-824ddd00-c19c-11e8-8ae4-576a109136e1.png)

But klakSpout sources are still black like this:
![sput-dx11-cpu-sender-not-working](https://user-images.githubusercontent.com/5880119/46081363-9e517e80-c19c-11e8-8a97-3635a6ef16f3.png)

**Comment by keijiro** [comment]
Thanks for providing the information.

I noticed that the window title contains the word "CPU" -- indicating that it's running in the CPU mode. It means your PC doesn't support NV_DX_interop extension, so the textures are not actually shared between apps (transferred via CPU instead).

I wonder if it actually doesn't. As far as I know, most GPUs support it (including AMD, Intel ones). Are you using the latest version of the graphics driver? If not, I'd strongly recommend updating it.

**Comment by erikhric** [comment]
We are trying to run this on computer with integrated intel graphics running on latest version of the driver. Name ' Spout DX11 CPU Sender' comes from the demo sender application.

![spout dx11 cpu sender-explanation](https://user-images.githubusercontent.com/5880119/46089512-f8f3d600-c1ae-11e8-8474-309d9719fe06.png)

**Comment by michalkrendzelak** [comment]
Hello keijiro,
I am working on the project mentioned above together with Erik. I would like to ask what is the difference between spout inputs that I see in resolume:
- Direct show capture devices / Spout Cam 1
- Spout / [sender name for example ' Spout DX11 CPU Sender' ]
(because first one works with demo sender, other not + for all other builds we have no option : 'Direct show capture devices / Spout Cam 1')

Thank you very much for your support.
![resolume-spout inputs](https://user-images.githubusercontent.com/43613726/46090307-bf23cf00-c1b0-11e8-8384-3539702f3080.png)

**Comment by keijiro** [comment]
Please ignore Spout Cam. You shouldn't use it if the application supports Spout.

**Comment by michalkrendzelak** [comment]
ok, understood. do you have any advice for us what should we do next?
Do you need any additional information from us? thx again.

**Comment by keijiro** [comment]
I don't have any PC that lacks NV_DX_interop support -- actually I didn't know that there is such a case with the current generation PCs.

I'd admit I have no workaround for this problem. I'll think about how I can test it with my dev environment.

**Comment by Milkorva** [comment]
Hi Keijiro, 
Thanks for this Unity's spout version ! 
I just have one question. I have quite the same problem that other guys. When I play your scene exemple, Spout receiver shows me all the cameras but I've got only a black screen (with the name of the camera). I already check that I'm using DirectX 11 in my player settings. For informations, I don't have Spout problem with other softwares. I send you in attached file a screenshot of my setup. 

Do you have any ideas of what it's going wrong ? 
Thanks so much. 

![spout](https://user-images.githubusercontent.com/9623724/53298436-670bfa00-382e-11e9-85b2-0234bbd38734.JPG)

**Comment by keijiro** [comment]
@Milkorva Thanks for reporting. Could you send the [Editor log](https://docs.unity3d.com/Manual/LogFiles.html) file?

**Comment by Milkorva** [comment]
Here it is :) 

[Editor.log](https://github.com/keijiro/KlakSpout/files/2897843/Editor.log)

**Comment by keijiro** [comment]
Hmm, weird. According to your screenshot, the receiver is running in the memoryshare mode. It's only used when the hardware doesn't support direct GPU sharing.

Could you try changing configurations to disable it? I'm not sure how to do it because it's not used by default.

**Comment by Milkorva** [comment]
You're totally right ! For a project I changed the Spout settings. I put them back and it works perfectly now!
Well done ! :)

**Comment by keijiro** [comment]
Thanks for shaking it out. I'll add it to the documentation.

**Comment by keijiro** [comment]
The CPU mode support is going to be removed in Spout SDK 2.007, so I'd like to abandon the CPU mode support in this plugin.
