### ISSUE TITLE
Not Sending when Graphics set to Lightweight Pipeline

### ISSUE THREAD

**Issue by petecleary** [keijiro/KlakSpout#23]
I have no issues in running Spout Sender on a project with no scriptable render pipeline set, as soon as I assign a Lightweight Pipeline to generate shaders using the Shader Graph the sender fails.

**Comment by keijiro** [comment]
Did you use the render texture mode? At the moment it doesn't support SRP (LWRP/HDRP) in the camera capture mode. Please refer to the README for details.

**Comment by petecleary** [comment]
Thank you, it works when set to a texture as you suggest.
