### ISSUE TITLE
Unity Fatal Crash after adding Spout Receiver

### ISSUE THREAD

**Issue by Tilix4** [keijiro/KlakSpout#24]
This is related to #19 that I cannot reopen then I create a new issue.

Unity version : 2018.2.17f1

import KlakSpout.unitypackage v0.2
Create Empty
Add Component Spout Receiver
Crash

Sender works perfectly.

**Comment by keijiro** [comment]
Thanks for reporing the issue. It's fixed in the latest version.

https://github.com/keijiro/KlakSpout/releases/tag/v0.2.3

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen if it sill reproduces.
