### ISSUE TITLE
Unity 2019.1.0f1 All compiler errors have to be fixed

### ISSUE THREAD

**Issue by newemka** [keijiro/KlakSpout#29]
I just wanted to try Quad but it doesn't run

**Comment by keijiro** [comment]
This issue is came from packages that are incorrectly added by the Unity version upgrader. It can be fixed by removing "Multiplayer HLAPI" and "XR Legacy Input Helpers" packages using Package Manager.

**Comment by keijiro** [comment]
I'm closing the issue now. Please feel free to reopen for further questions.

**Comment by newemka** [comment]
Thank you so much, it works, I'm sorry I should start to learn unity from the begining instead of trying to learn by testing your projects.

**Comment by keijiro** [comment]
FYI, I updated the project so that now it can be opened with Unity 2019.1.0f1.
