### ISSUE TITLE
Wrong condition for recreating _receivedTexture

### ISSUE THREAD

**Issue by Esam-Bustaty** [keijiro/KlakSpout#30]
I believe [this](https://github.com/keijiro/KlakSpout/blob/e70b2fd0978ee31f9aecaa04b900f91865527535/Assets/Klak/Spout/Runtime/SpoutReceiver.cs#L145) line should be: 

`if (_receivedTexture != null) Util.Destroy(_receivedTexture);`

**Comment by keijiro** [comment]
Thanks for pointing it out. Yes, you're right. I fixed this issue in the latest update.

I'm closing this issue now. Please feel free for further problems.
