### ISSUE TITLE
Dont't run in Unity2019.1 with HDRP

### ISSUE THREAD

**Issue by TxTx123** [keijiro/KlakSpout#32]
I can't use SpoutKlak Unity2019.1 with HDRP mode.
It works with Unity2018.3 + HDRP.

Please update Spout Klak.
I love it very much.

**Comment by keijiro** [comment]
I confirmed it works without any problem on Unity 2019.1.0f2 with HDRP 5.13.0.

Please re-check if there is any issue in other parts of the project. If it still reproduces, please provide a minimum project that can reproduce the issue.

**Comment by keijiro** [comment]
Now I'm closing this issue. Please feel free to reopen if it still reproduces.
