### ISSUE TITLE
SpoutSender not working on High Definition RP Project

### ISSUE THREAD

**Issue by txusillo** [keijiro/KlakSpout#33]
SpoutSender is not working properly on a High Definition RP. 

Ways to reproduce this issue:
-Create a New Project and select Hight Definitio Rp.
-Import KlakSpout package
-Attach SpoutSender Script to Main Camera

Unity Version: 2018.3.12f1

Would you help me with this issue? 

Thank you for your work, it has been really useful

**Comment by keijiro** [comment]
Please note that the Camera Capture mode isn't supported in scriptable render pipelines. You have to use the Render Texture mode. Please take a look into `README.md` for further details.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by txusillo** [comment]
Thank you for replying. I did read the readme, but didn't know that the camera was set in Scriptable Render Pipeline (Im new to Unity). 

By Render Texture Mode, you mean render the camera that is using a scriptable render pipeline as a texture, apply it to a plane, and then add a normal camera with the spoutsender script?

Thank you.
