### ISSUE TITLE
Auto select first available receiver

### ISSUE THREAD

**Issue by benkuper** [keijiro/KlakSpout#34]
Hey,
awesome plugin, as always with Keijiro :)
When I created Unity Spout Plugin before Klak was out (and better), the default behavior when texture name is empty in a Spout Receiver was to take the first in list. 
It's very useful to be able to quickly see something / switching between senders, or not having to set it up when exporting for a system that will only have one shared texture, but we don't know from which software (I'm exporting an app for another artist and I don't know which software he will use for generating the texture).
Is it something that you would implement, either as a default behavior or a checkbox (or option in the dropdown "auto select / first available") ?

**Comment by keijiro** [comment]
You can connect to the first available sender by using a script like following:

```
var names = SpoutManager.GetSourceNames();
if (names.Length > 0) GetComponent<SpoutReceiver>().sourceName = names[0];
```
