### ISSUE TITLE
Question: Spout for 360 Output

### ISSUE THREAD

**Issue by Aoost** [keijiro/KlakSpout#35]
Hi Keijiro, 

First off thank you for all your awesome work. 

I was wondering if you could recommend software to output 360 video content to other software (ie. touch designer) instead of only the Game view width?

**Comment by keijiro** [comment]
Unfortunately, I have no experience on 360-degree video. I'd recommend asking an expert rather than me.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further issues.
