### ISSUE TITLE
Dont't run in Unity2019.1 with post processing.

### ISSUE THREAD

**Issue by sipv1612** [keijiro/KlakSpout#36]
I can't use SpoutKlak Unity2019.1 with post processing component in camera.
Please fix it.
Thank you.

**Comment by keijiro** [comment]
Thanks for reporting the issue. Could you provide a minimum project that can reproduce the issue?

**Comment by sipv1612** [comment]
I've attached the file included the project and a screenshot. (I use resolume to display spout signal). Thank you for your time!
https://drive.google.com/file/d/1ybcMOpRazMPgLfW7ybvH73NqeoiyCeok/view?usp=sharing

**Comment by keijiro** [comment]
It works correctly with the [SpoutReceiver](https://github.com/leadedge/Spout2/blob/master/DEMO/SpoutReceiver.exe) example in the SDK.

I noticed that the output from Post Processing Stack doesn't contain alpha -- in other words, alpha = 0.0 for all pixels. That might be why it got black on the Resolume side. You should stop using alpha or look for a way to recover alpha after post processing.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further problems.
