### ISSUE TITLE
IL2CPP build issue

### ISSUE THREAD

**Issue by sasa42** [keijiro/KlakSpout#38]
Unity 2019.1.14
Windows 10
Scripting Backend IL2CPP
Spout 0.2.4

I get following build error

KlakSpoutGlobal.h(6): fatal error C1083
cannot open “Spout/SpoutDirectX.h
No such file or directory

Scripting Backend Mono works fine.

**Comment by sasa42** [comment]
Hi, 
we rely heavily on Spout in our scenario

Unity 2019.2.10
 Windows 10
 Scripting Backend IL2CPP
 Spout 0.2.4

I get a still following build error

KlakSpoutGlobal.h(6): fatal error C1083
 cannot open “Spout/SpoutDirectX.h
 No such file or directory

We would get some 6% to 8%
performance benefit with an IL2CPP build.

Some questions.
Do you think it is possible to allow IL2CPP builds with Spout?
When you not plan to support it, could you give me a hint what to do?
Thanks.

**Comment by keijiro** [comment]
Something wrong is happening on your side. `KlakSpoutGlobal.h` shouldn't exist in a project directory. Did you import the plugin using `KlakSpout.unitypackage`? I'd recommend removing KlakSpout files from your project and re-importing it using the latest `KlakSpout.unitypackage` file.

**Comment by keijiro** [comment]
I'm closing this issue now as I assume it has been already solved. Please feel free to reopen for further questions.
