### ISSUE TITLE
Not working in SRP

### ISSUE THREAD

**Issue by phields** [keijiro/KlakSpout#41]
OnRenderImage is not support in SRP/LWRP
https://docs.unity3d.com/Packages/com.unity.render-pipelines.lightweight@5.10/manual/lwrp-builtin-feature-comparison.html

**Comment by phields** [comment]
solved with using render texture mode

**Comment by phields** [comment]
Could I put this input SRP with CustomRenderPassFeature?

**Comment by keijiro** [comment]
As far as I know, `CustomRenderPassFeature` only works with URP (LWRP). This plugin should be compatible with HDRP too (I mainly use it with HDRP).

Please use the render texture mode for a while. I'd like to add a better solution, but I don't have any good idea at the moment.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
