### ISSUE TITLE
Source Name property for Spout Sender camera component?

### ISSUE THREAD

**Issue by violetforest** [keijiro/KlakSpout#42]
Hey, is it possible to add a source name property to the Camera capture mode sender component? 

I have 4 cameras in a unity scene for a projection mapped room and I'm getting instructions to "send Textures to the mapping system via Spout. The textures Spout names to share are "x", "y", "z", and "a"."

Thanks

**Comment by keijiro** [comment]
SpoutSender uses its name (GameObject's name) as a spout source name, so what you have to do is just renaming your game objects to "x", "y", "z" and "a".

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
