### ISSUE TITLE
Float texture receiver not working with negative values

### ISSUE THREAD

**Issue by prisonerjohn** [keijiro/KlakSpout#44]
I'm sending a texture in `RG_32F` format.

It appears to be coming in correctly in both the Spout Receiver example and Touch Designer, but not in Unity. The Unity receiver looks like it's flipping the negative values to always be positive. I am setting up my render texture with format `R32G32B32A32_SFLOAT`.

![Spout-Receiver](https://user-images.githubusercontent.com/119702/71835604-f8b7db00-307f-11ea-9711-46ab37ecff92.png)
![Spout-TouchDesigner](https://user-images.githubusercontent.com/119702/71835605-f8b7db00-307f-11ea-9960-3b59e01589d3.png)
![Spout-Unity](https://user-images.githubusercontent.com/119702/71835606-f8b7db00-307f-11ea-9f39-746bb3557cd3.png)

I think it's a bug, but please advise if you have any suggestions for fixing it. Thanks!

**Comment by keijiro** [comment]
It's one of the limitations of the current implementation; The texture format is hardcoded as ARGB32.

If you need a workaround, try modifying the following lines.

https://github.com/keijiro/KlakSpout/blob/master/Assets/Klak/Spout/Runtime/SpoutReceiver.cs#L139

https://github.com/keijiro/KlakSpout/blob/master/Extras/KlakSpoutPlugin/KlakSpout/KlakSpoutSharedObject.h#L127

**Comment by prisonerjohn** [comment]
Ok, thanks for this! 
I added an editable field for the `TextureFormat` and that seems to work. If I have a bit more bandwidth, I'll clean it up and try to get the format from the incoming texture raw pointer and send a PR.

**Comment by ioannismihailidis** [comment]
I'm streaming point clouds from touchdesigner to unity. NDI has no support for floats, so I tested a way with spout. Besides of the texture format issue, I had to disable the gamma lut in "Blit.shader" to fix distortion of 3d positions:

```
        //#if !defined(UNITY_COLORSPACE_GAMMA)
        //col.rgb = GammaToLinearSpace(col.rgb);
        //#endif
```

**Comment by keijiro** [comment]
I created a new TODO issue: #71 

I close this issue for now. Please follow the new issue if you're still interested in it.
