### ISSUE TITLE
One sender always remains in receiver source list even after all senders are closed

### ISSUE THREAD

**Issue by Barbelot** [keijiro/KlakSpout#45]
Hello,
Thank you for this amazing plug-in !

I am trying to implement an automatic selection of the first source available in the receiver (as mentionned in https://github.com/keijiro/KlakSpout/issues/34) and I run into a problem where once at least one sender as been seen, the receiver name list never goes back to empty even when I close all senders. One sender always remains even though it is not sending anymore. This remaining sender is not always the same and additional senders are added and removed fine. 

Example : 
1. No senders -> source list = []
2. Start sender A -> source list = [A]
3. Close sender A -> source list = [A] (problematic, the list should be empty)
4. Start sender B -> source list = [B] (Adding another sender removed the remaining A)
5. Start sender A -> source list = [B, A]
6. Close sender A -> source list = [B]
7. Close sender B -> source list = [B] (problematic, the list should be empty)

I need to close all my Spout sending programs and restart Unity to get back to an empty sender list.

Do you have any idea of what may be causing this issue ?

**Comment by keijiro** [comment]
Fixed in 2a42ab8
