### ISSUE TITLE
Stops working when switch platform to UWP 

### ISSUE THREAD

**Issue by CharStiles** [keijiro/KlakSpout#48]
Hi!
Thanks for making this plugin. 
I found when you make a blank project & add klakSpout to the camera & make sure it works, then switch the build platform to UWP (Universal Windows Platform) in build settings then hit play klak no longer sends to spout.
Unity 2019.3.3f1
Im using spout DX11 Receiver to test it
Best,
Char

**Comment by keijiro** [comment]
Unfortunately, Spout doesn't support UWP.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by CharStiles** [comment]
Thank you so much for your fast response! One more quick question if I can- is there anyway to share a texture out of a UWP build? NDI? 
Again, I appreciate your hard work

**Comment by keijiro** [comment]
NDI doesn't support UWP, either. I'm afraid that there is no convenient way to share a texture from a UWP app.
