### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sinokgr** [keijiro/KlakSpout#5]
Hi there,
I created two projects (sender/receiver) and I hit play in both (with background on in the player settings) and it works fine. When I built the projects and tried to do run the builds, they didn't work. Any idea why?

**Comment by keijiro** [comment]
KlakSpout doesn't support 32-bit (x86) target. Could you make sure that the target architecture is set to x86_64?

**Comment by sinokgr** [comment]
yep, that fixed the problem. Thanks 😄
