### ISSUE TITLE
Does Spout work in Unity when using HDRP ?

### ISSUE THREAD

**Issue by timwei919** [keijiro/KlakSpout#52]
Hello,
I am using Unity's Visual Effect Graph function,
To use this function, it must be under HDRP.

So I would like to ask if Spout can be executed in this situation?
Because I add the spout sender component on Camera (like the way we are familiar with),
However, the image cannot be transmitted.

So I would like to ask if Spout(Not even NDI) can run under HDRP? is there any other reason?

Thanks!

**Comment by keijiro** [comment]
It supports HDRP but you have to use the render texture mode. Please see README.md for details.

**Comment by timwei919** [comment]
Thank you very much for your assistance, I missed this feature.
