### ISSUE TITLE
SpoutSender not sending render texture when using LWRP

### ISSUE THREAD

**Issue by UnquotidianVi** [keijiro/KlakSpout#53]
I was able to get everything working on a fresh Unity project. But I have two older projects which I have tried to link to Spout, by using the render texture feature. Render texture is updating, and SpoutSender contains a reference to the correct Render Texture, also the SpoutSender is in an active gameobject.

Only commonality that I could think between these two older projects is that they both use LWRP. The other one is on Unity version 2019.3.11f1 and the other is on version 2019.4.2f1
![image](https://user-images.githubusercontent.com/22080933/87858385-37372800-c936-11ea-9b49-69f69ee970ad.png)
![image](https://user-images.githubusercontent.com/22080933/87858392-3ef6cc80-c936-11ea-8325-4d91a7e87bd3.png)

**Comment by keijiro** [comment]
First of all, please check if the project is using the DX11 graphics API mode.

**Comment by UnquotidianVi** [comment]
I actually was able to find the issue. I had accidentally left the build target to be targeting Linux. Sorry for the issue.
