### ISSUE TITLE
Modify the param “format” of the function "setupSender"  to "DXGI_FORMAT_B8G8R8A8_UNORM",cann't receive the i

### ISSUE THREAD

**Issue by xiaoge777888** [keijiro/KlakSpout#55]
Modify code:
//const auto format = DXGI_FORMAT_R8G8B8A8_UNORM;
const auto format = DXGI_FORMAT_B8G8R8A8_UNORM;
result:
cann't receive Image.

**Comment by keijiro** [comment]
I think you also have to modify C# code.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further issues.
