### ISSUE TITLE
Any plan to add SharedMemory mode support?

### ISSUE THREAD

**Issue by phields** [keijiro/KlakSpout#56]
The 2.007 SDK has improved the memory shared mode.
it's not based on CPU now.
Memory share mode improved
Performance of shared memory functions has been improved by using
multiple pixel buffers to load from and upload to OpenGL textures and
remains a backup where hardware is not texture share compatible.

**Comment by keijiro** [comment]
Yes, but I'm still waiting for 2.007 official release.

**Comment by phields** [comment]
I created a branch that upgraded to 2.007 and it's working fine now.
https://github.com/phields/KlakSpout
Seems like KlakSpout doesn't have too many parts that need to be changed, I hope this helps!
In the meantime, I'm looking for ways to add memory sharing compatibility...
