### ISSUE TITLE
Check last frame time for feed?

### ISSUE THREAD

**Issue by BenWoodford** [keijiro/KlakSpout#59]
(Fantastic little plugin by the way, saved me loads of time)

Is there a way to grab the timestamp of the last successful frame from a feed? I'd like to check it and if one hasn't been provided in a while, and handle it as though the submitting application is lagging behind for whatever reason and tell the user, rather than leaving them with a static image.

**Comment by keijiro** [comment]
Unfortunately, it's not possible. Spout is just a wrapper class for shared memory, so it can't detect modifications on it.

You can check if the sender is still alive by comparing `_plugin` with `System.IntPtr.Zero`.

https://github.com/keijiro/KlakSpout/blob/master/Packages/jp.keijiro.klak.spout/Runtime/SpoutReceiver.cs#L64
