### ISSUE TITLE
DX12 support

### ISSUE THREAD

**Issue by sasa42** [keijiro/KlakSpout#60]
Hi,

i had a conversation with leadage from spout2.
https://github.com/leadedge/Spout2/issues/55#issue-732417038

he pointed me to the D3D1211On12 feature which is enableing Spout compatibility for ray tracing
https://github.com/leadedge/Spout2/issues/55#issuecomment-719066717

Do you see a chance to get DX12 support for KlakSpout?

Your NDI DX12 solution works great but it s to slow for our use case.

**Comment by keijiro** [comment]
The short answer is no.

Even though if I used the 11-on-12 features, I would have to spend lots of time for R&D.

I'm still waiting for the Spout 2.007 release. Upgrading to 2.007 is the most important task for this plugin. All the other things are paused until it happens.

**Comment by keijiro** [comment]
I'll continue considering DX12 support on #61
