### ISSUE TITLE
Can't work with HDRP?

### ISSUE THREAD

**Issue by Tongzhou-Yu** [keijiro/KlakSpout#66]

**Comment by keijiro** [comment]
It does work on HDRP.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Tongzhou-Yu** [comment]
Once Project Settings>Graphics>SRP Settings is none, both Spout and Spyhon work well, but if SRP Settings is "HDRenderPipelineAsset", either can't work (nothing shows in TouchDesigner's syphonspoutin.

**Comment by keijiro** [comment]
Did you try the render texture mode? As noted on README, the camera capture mode is not supported on SRP (URP/HDRP).

**Comment by Tongzhou-Yu** [comment]
Thanks, but still can't work with Spyhon, and have found there is the same question on KlakSpyhon page. Looking for any solution for Spyhon.

**Comment by keijiro** [comment]
First of all, don't mix up Spout and Syphon. They're completely different technologies.

Please make it clear if you're trying to use Spout on Windows, or Syphon on Mac.
