### ISSUE TITLE
Multiple-Cameras ?

### ISSUE THREAD

**Issue by albrrt** [keijiro/KlakSpout#67]
Hello,

We have a project where we use 3 cameras to render our scene - because of conflicts with transparent shaders, depth buffer and the depth-of-field effect of the post-processing stack. 

If I add a Spout Sender component to each of these 3 cameras, will KlakSpout automatically merge the output of these cameras into a single sprout stream?

Apologies for the question - we are unable to test this at the moment but we are interested in using this plugin for large-scale projection mapping environments. #

Thank you for your help

**Comment by keijiro** [comment]
> If I add a Spout Sender component to each of these 3 cameras, will KlakSpout automatically merge the output of these cameras into a single sprout stream?

No.

**Comment by keijiro** [comment]
You have to composite them before giving them to SpoutSender.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
