### ISSUE TITLE
Creating/Destroying Spout Senders programmatically works in the Editor but not in build 

### ISSUE THREAD

**Issue by Harvey3141** [keijiro/KlakSpout#7]
Hi, 

I've have an issue where creating or destroying a Spout sender in code results in a crash in a build, but works in the Editor

I've tested with Unity 5.6 and 2017. 

Test case - Using the following to destroy and create the SpoutSender component. (Maybe I'm missing something obvious)

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.D))
        {
            if (GetComponent<Klak.Spout.SpoutSender>()) Destroy(GetComponent<Klak.Spout.SpoutSender>());
        }

        if (Input.GetKeyDown(KeyCode.C))
        {
            if (!GetComponent<Klak.Spout.SpoutSender>()) gameObject.AddComponent<Klak.Spout.SpoutSender>();
        }
    }
}

Thanks, 

Harvey

**Comment by Harvey3141** [comment]
Interestingly I don't get a crash in the build when running on different haredware . I've done some testing on the available hardware I have. 

**Machine 1** 
Windows 10 , Nvidia GTX 980
Editor - OK
Build - Crash

**Machine 2**
Windows 10 , Nvidia Quadro P6000
Editor - OK
Build - Crash

**Machine 3**
Windows 10,  Macbook Pro 2017 ,AMD Radeon Pro 455 
Editor - OK
Build - OK

**Comment by Harvey3141** [comment]
Possibly related to this issue

https://answers.unity.com/questions/1339292/build-crash-directx-11-unity-56.html

**Comment by keijiro** [comment]
I think this issue is not reproducible with the latest version. Please feel free to reopen if you meet the same issue.
