### ISSUE TITLE
Spout Receiver flips the texture by default

### ISSUE THREAD

**Issue by fortminors** [keijiro/KlakSpout#74]
Hello!

I found out that KlakSpout flips the texture internally by default somewhere in the KlakSpout.dll by both X and Y axes.
To reproduce, just launch a SpoutSender.exe demo and observe the texture getting flipped in the Unity project.

Could you please remove it? This doesn't seem to be required for every use case.

Thanks!

**Comment by keijiro** [comment]
Which version are you using?

If I remember correctly, it's fixed in v2.0.0.

**Comment by fortminors** [comment]
Thank you for a quick reply. My manifest.json says `"jp.keijiro.klak.spout": "2.0.3"`

**Comment by keijiro** [comment]
Thanks for the clarification.

That issue doesn't reproduce on my side. Could you provide a minimal project that reproduces the issue on your side?

**Comment by fortminors** [comment]
Yes sure, where should I send it to you?

**Comment by keijiro** [comment]
Zip and attach it to a reply.

Exclude the Library folder when zipping it. Then you can make the file small enough, like <1MB.

**Comment by fortminors** [comment]
[Test.zip](https://github.com/keijiro/KlakSpout/files/7160926/Test.zip)

Here you go, thank you!

**Comment by keijiro** [comment]
I checked your setup and found that your "Plane" object is placed upside down.

Rotate it correctly, or simply use the Quad mesh.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen it for further problems.
