### ISSUE TITLE
The camera capture method with HDRP doesn't work on release builds

### ISSUE THREAD

**Issue by maoge124** [keijiro/KlakSpout#75]
No showing when I run the exe, Unity use HDRP, SpoutSender.Capture method = Camera.
Unity Editor is OK, no showing with exe.

**Comment by keijiro** [comment]
Could you share a minimal project that reproduces the issue?

**Comment by maoge124** [comment]
> Could you share a minimal project that reproduces the issue?

I have sent it to your email：keijiro@gmail.com.
Thanks

**Comment by maoge124** [comment]
> Could you share a minimal project that reproduces the issue?
I successfully showing the exe frame by spout when I use the _Unity DevelopmentBuid_.But the exe  that build by Release is no showing.

**Comment by keijiro** [comment]
I confirmed that the issue is caused by HDRP (it works correctly on URP). I reported the issue to the QA team. Please wait for their action. Until then, please understand that this is a known issue. You should use the render texture mode instead as a workaround.

**Comment by keijiro** [comment]
I verified that this issue has been fixed on 2022.1 beta. Also the same fix is coming to 2021.2.9.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it if it still reproduces.
