### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by vadimkrutovlv** [keijiro/KlakSpout#78]
I would like to use this plugin on my mac is there any plan to add mac support?

**Comment by keijiro** [comment]
Spout is a kind of a Windows API wrapper. Obviously, it only runs on Windows.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by vadimkrutovlv** [comment]
@keijiro thanks for explanation is there any alternative for mac?

**Comment by keijiro** [comment]
Syphon or NDI.
