### ISSUE TITLE
Error: Type or namespace does not exists

### ISSUE THREAD

**Issue by sissa0** [keijiro/KlakSpout#86]
Hey, I try to run KlakSpout in Unity Version 2021.2.19f1 but I always get this Error:

Assets\Script\SourceSelector.cs(2,19): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets\Script\SourceSelector.cs(9,22): error CS0246: The type or namespace name 'Dropdown' could not be found (are you missing a using directive or an assembly reference?)

I didnt change anything of that and also in older versions it is not working :/ Would be a great help to get this working!

**Comment by keijiro** [comment]
Please try adding the Unity UI package using the Package Manager window.

**Comment by sissa0** [comment]
Wow you are my hero! It works :) Thanks you so much!
