### ISSUE TITLE
Better resolution ?

### ISSUE THREAD

**Issue by Gildas310** [keijiro/KlakSpout#87]
Hello,
thank you for your work.

I have low resolution of my spout video in Unity.
How can I have better resolution in Unity please ?

I send the video from Madmapper which is in 4k, I receive it in (may be) SD 640x480.

**Comment by keijiro** [comment]
Please try using a render texture with the 4k resolution to receive image.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it if it still reproduces.

**Comment by Gildas310** [comment]
You are right for the size of the texture
It's perfect.
Thank you.
