### ISSUE TITLE
Spout sender and Fulldome view

### ISSUE THREAD

**Issue by PockPocket** [keijiro/KlakSpout#88]
Hi,

I'm having difficulty sending a RenderTexture of my fulldome game view to Touch.Designer via Spout. It seems that I can only send the default camera view without the fulldome effect.

![image](https://user-images.githubusercontent.com/73412598/167196904-53e7ef2a-23e5-4950-846e-76953e64d291.png)

I feel that there's something I should do with the Cubemap Fbo slot attached to the fulldome camera component (see picture) but I don't know what exactly.

Presenting in a Dome on May 16th, this real-time workflow would truly be a game changer.

Any input on how to get this working would be really appreciated.

Cheers,
Mathieu.

**Comment by PockPocket** [comment]
Small update on this issue, my cube map is now receiving the information from the fulldome script and a 4k x 4k white texture is being live streamed via spout to Touch designer.

![image](https://user-images.githubusercontent.com/73412598/167208704-ad94b162-d820-4c7a-a4ef-bd394b2190ed.png)


RenderTexture settings:
![image](https://user-images.githubusercontent.com/73412598/167208769-b1efa279-7c5a-44ad-bc1e-94ad951b80e2.png)


My camera and the fulldome script are two separated obejcts:
![image](https://user-images.githubusercontent.com/73412598/167208573-7914bb1b-e127-4bbd-be40-78b6c9c5a979.png)


Any ideas on why the image in Touch Designer appears all white ?

Mathieu.

**Comment by keijiro** [comment]
Spout doesn't support cubemap textures.

**Comment by PockPocket** [comment]
Oh ok that explains it. Thanks for the input. Would you know of a work around for this ? Changing the aspect ratio in Unity to force a dimension through Touch Designer didn't work so I was hoping it could work via RenderTexture.

**Comment by keijiro** [comment]
I think flattening with equirectangular projection is the most common approach.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it if the original problem still reproduces.

**Comment by PockPocket** [comment]
I'd like to project some visuals in a dome so I was more thinking about something that would allow Unity to send that fishey fulldome effect via spout. Thanks for the help.
