### ISSUE TITLE
Madmapper problem

### ISSUE THREAD

**Issue by Gildas310** [keijiro/KlakSpout#89]
Hello Keijiro,

I send a spout video from max msp jitter to unity, then I send Unity game view in Madmapper.
Without any reason, my spout workflow doesn't work anymore.

Spout receiver in Madmapper receive the video of Max Msp jitter, not Unity's one.
When I create fresh project of the third softwares, it works, then I Stop unity game, or I build unity game, madmapper does source change for no reason.
Do you have an idea to solve this please ?

(It's incredible I work with this worflow for few weeks)

I use Unity 2021.3.2f1

Thank you

**Comment by keijiro** [comment]
I don't have any idea. I think it's a by-design behavior of MadMapper.

**Comment by Gildas310** [comment]
Ok.

I have converted my project from 3d (Core) to 3D (HDRP) in order to use camera spout sender instead of the game view.
It looks like working.

Thank you for your answer and for your work.

**Comment by keijiro** [comment]
Sure. I close this issue as "not reproducible".
