### ISSUE TITLE
Crashing while taking a build

### ISSUE THREAD

**Issue by xeonification** [keijiro/KlakSpout#9]
Unity is crashing constantly while trying to build my application with spout sender on the camera. When I turn off the component I am able to build the application.

**Comment by keijiro** [comment]
Which version of Unity are you using?

**Comment by xeonification** [comment]
2017.3.0 .it was working yesterday. Is there anyways I can give you the
logs ?

**Comment by Andergraw** [comment]
First, thank you for your great work, Keijiro, it is absolutely amazing.
We are having exactly the same problem working with Spout, constant crashes on build. 
Using Unity 2017.4.0.
Cheers,

**Comment by keijiro** [comment]
First of all, please check the build architecture set to x86_64. KlakSpout doesn't support the 32-bit (x86) architecture.

If you still have problem with that, please send a minimum project that reproduces the problem.

**Comment by Andergraw** [comment]
Yep, in my case it was because of that.
Thank you very much!

**Comment by keijiro** [comment]
FYI: I added x86 support in the [latest version](https://github.com/keijiro/KlakSpout/releases/tag/v0.1.3).

I'm closing this issue. Please feel free to reopen for further questions.
