### ISSUE TITLE
Spout Only sending signal on one machine

### ISSUE THREAD

**Issue by Alberthalbautomaten** [keijiro/KlakSpout#92]
Hey there! 

Great Plugin mate! I really don't get what i did wrong but your Plugin only sends a signal on one machine. On any other with the exact same Setup it does not. Is this an issue you are aware of maybe?

**Comment by Alberthalbautomaten** [comment]
Running a development build i also get 

_Fallback handler could not load library_ for every .dll of klakspout.

Then i get a _DllNotFoundException: KlakSpout assembly:<unknown assembly> type:<unknown type> member:(null)_

**Comment by keijiro** [comment]
Please keep one topic per one ticket.

**Comment by keijiro** [comment]
> On any other with the exact same Setup it does not.

- Is there any warning/error message?
- What are the specifications of those machines?

**Comment by keijiro** [comment]
> Fallback handler could not load library for every .dll of klakspout.
> Then i get a DllNotFoundException: KlakSpout assembly: type: member:(null)

Did you build the project with specifying the 64-bit architecture? (KlakSpout doesn't support 32-bit)

**Comment by Alberthalbautomaten** [comment]
> > Fallback handler could not load library for every .dll of klakspout.
> > Then i get a DllNotFoundException: KlakSpout assembly: type: member:(null)
> 
> Did you build the project with specifying the 64-bit architecture? (KlakSpout doesn't support 32-bit)

That fixes that Problem. Thank you!

**Comment by Alberthalbautomaten** [comment]
> > On any other with the exact same Setup it does not.
> 
> * Is there any warning/error message?
> * What are the specifications of those machines?

There are no Warnings. 

The working Machine has a 3070ti
Got it to work on a TITAN X now
It does not work on a mobile 3060

**Comment by Alberthalbautomaten** [comment]
The Receiver seems to see the Signal but displays a plain white image.

**Comment by keijiro** [comment]
It should run on RTX 3060 Mobile.

I assume that the machine is a laptop, and I guess it has an integrated GPU too (Intel HD Graphics or something like that). Is it possible to explicitly disable the integrated one?

**Comment by Alberthalbautomaten** [comment]
> It should run on RTX 3060 Mobile.
> 
> I assume that the machine is a laptop, and I guess it has an integrated GPU too (Intel HD Graphics or something like that). Is it possible to explicitly disable the integrated one?

Disabling the Integrated Unit did not help. However this is what it reads from the sender.

![Spout](https://user-images.githubusercontent.com/90780912/191474385-a38d4295-53be-48cd-ac86-868dd1554cde.PNG)
