### ISSUE TITLE
Spout output very banded

### ISSUE THREAD

**Issue by mangelhoyos** [keijiro/KlakSpout#98]
[Banded output](https://ibb.co/CmZN1GW)

Is there anyway that i can set the Spout sender to have 32 bit full float precision to avoid having those bands on the output for the recievers? I'm currently using the Texture Capture method and a render texture in HDRP.

**Comment by keijiro** [comment]
I think you can change the format by modifying the following lines:

https://github.com/keijiro/KlakSpout/blob/main/Plugin/Sender.h#L58

https://github.com/keijiro/KlakSpout/blob/main/Packages/jp.keijiro.klak.spout/Runtime/SpoutSender.cs#L43
